; ─────────────────────────────────────────────────────────
;  BETA XRP  (RP2040 / Pico W) ← use this for the older board
; ─────────────────────────────────────────────────────────
 [env:xrp_beta]
 platform  = https://github.com/maxgerhardt/platform-raspberrypi.git
 board     = rpipicow
 framework = arduino

 board_build.core = earlephilhower

 lib_deps =
     adafruit/Adafruit LSM6DS@^4.7.2
     adafruit/Adafruit BusIO@^1.16.1
     adafruit/Adafruit Unified Sensor@^1.1.14

monitor_speed = 115200